JSError: never fail with invalid getter target" (#1621) (#16)
Summary:
Pull Request resolved: https://github.com/facebook/hermes/pull/1621

JS developers expect this to work and print "undefined":
```js
function MyEror() {
    this.message = "MyError";
}
MyError.prototype = Object.create(Error.prototype);
try {
    throw new MyError();
} catch (e) {
    print(e.stack);
}
```

We give it to them by preventing the getter from throwing errors. In V8
this is implemented differently by attaching the getter to the actual
instance.

Arguably, this makes sense, because property reads shouldn't throw.

Add and update tests.

- Grafted path static_h to hermes

Reviewed By: avp

Differential Revision: D69757360

fbshipit-source-id: 216e870e82c941a985020202dc14aa5948164da8

Co-authored-by: Tzvetan Mikov <tmikov@meta.com>